2024-05-04 19:30:16,014 - uvicorn.error - INFO - Will watch for changes in these directories: ['/mnt/e/cura/cura_backend']
2024-05-04 19:30:16,015 - uvicorn.error - ERROR - [Errno 98] Address already in use
2024-05-04 19:30:40,263 - uvicorn.error - INFO - Will watch for changes in these directories: ['/mnt/e/cura/cura_backend']
2024-05-04 19:30:40,264 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-05-04 19:30:40,264 - uvicorn.error - INFO - Started reloader process [73277] using statreload
2024-05-04 19:30:40,365 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-04 19:30:40,967 - main - <module> - INFO - program_started
2024-05-04 19:30:40,968 - uvicorn.error - INFO - Started server process [73279]
2024-05-04 19:30:40,968 - uvicorn.error - INFO - Waiting for application startup.
2024-05-04 19:30:40,968 - uvicorn.error - INFO - Application startup complete.
2024-05-05 11:33:50,061 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-05 11:33:50,131 - uvicorn.error - INFO - Shutting down
2024-05-05 11:33:50,233 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-05 11:33:50,234 - uvicorn.error - INFO - Application shutdown complete.
2024-05-05 11:33:50,234 - uvicorn.error - INFO - Finished server process [73279]
2024-05-05 11:33:50,458 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-05 11:33:51,102 - main - <module> - INFO - program_started
2024-05-05 11:33:51,103 - uvicorn.error - INFO - Started server process [205370]
2024-05-05 11:33:51,103 - uvicorn.error - INFO - Waiting for application startup.
2024-05-05 11:33:51,103 - uvicorn.error - INFO - Application startup complete.
2024-05-05 11:33:55,095 - uvicorn.access - send - INFO - 127.0.0.1:60532 - "GET /docs HTTP/1.1" 200
2024-05-05 11:33:55,262 - uvicorn.access - send - INFO - 127.0.0.1:60532 - "GET /openapi.json HTTP/1.1" 200
2024-05-05 11:34:17,875 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-05 11:34:17,896 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-05 11:34:17,915 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2012}>
2024-05-05 11:34:17,946 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-05 11:34:17,946 - root - runInTryCatch - INFO - Pagination
2024-05-05 11:34:17,946 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_0d68f33899814f458fc2ec6007a3fa24 LIMIT 10 OFFSET 0]
2024-05-05 11:34:18,143 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 10
2024-05-05 11:34:18,186 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-05 11:34:18,186 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4401, in get_pma_billing
    if not payload['add']:
KeyError: 'add'
2024-05-05 11:34:18,194 - root - get_pma_billing - INFO - None
2024-05-05 11:34:18,217 - uvicorn.access - send - INFO - 127.0.0.1:42182 - "POST /getPMABilling HTTP/1.1" 200
2024-05-05 11:34:51,834 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-05 11:34:51,853 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-05 11:34:51,872 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2012, 'add': False}>
2024-05-05 11:34:51,896 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-05 11:34:51,896 - root - runInTryCatch - INFO - Pagination
2024-05-05 11:34:51,897 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_2c96d2889e474ea0a6c9fdaa87aadeec LIMIT 10 OFFSET 0]
2024-05-05 11:34:52,089 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 10
2024-05-05 11:34:52,138 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-05 11:34:52,138 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-05 11:34:52,168 - uvicorn.access - send - INFO - 127.0.0.1:42470 - "POST /getPMABilling HTTP/1.1" 200
2024-05-05 11:40:33,096 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-05 11:40:33,128 - uvicorn.error - INFO - Shutting down
2024-05-05 11:40:33,229 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-05 11:40:33,229 - uvicorn.error - INFO - Application shutdown complete.
2024-05-05 11:40:33,229 - uvicorn.error - INFO - Finished server process [205370]
2024-05-05 11:40:33,390 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-05 11:40:33,950 - main - <module> - INFO - program_started
2024-05-05 11:40:33,950 - uvicorn.error - INFO - Started server process [205598]
2024-05-05 11:40:33,951 - uvicorn.error - INFO - Waiting for application startup.
2024-05-05 11:40:33,951 - uvicorn.error - INFO - Application startup complete.
2024-05-05 11:40:51,424 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-05 11:40:51,443 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-05 11:40:51,462 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2012, 'add': False}>
2024-05-05 11:40:51,484 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-05 11:40:51,484 - root - runInTryCatch - INFO - Pagination
2024-05-05 11:40:51,485 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_49436d1427dd46a3af08279fac59044c LIMIT 10 OFFSET 0]
2024-05-05 11:40:51,766 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 10
2024-05-05 11:40:51,877 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-05 11:40:51,877 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-05 11:40:51,962 - uvicorn.access - send - INFO - 127.0.0.1:50206 - "POST /getPMABilling HTTP/1.1" 200
2024-05-05 12:20:34,619 - uvicorn.access - send - INFO - 127.0.0.1:44130 - "GET /openapi.json HTTP/1.1" 200
2024-05-06 17:42:48,456 - uvicorn.error - INFO - Will watch for changes in these directories: ['/mnt/e/cura/cura_backend']
2024-05-06 17:42:48,457 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2024-05-06 17:42:48,457 - uvicorn.error - INFO - Started reloader process [7724] using statreload
2024-05-06 17:42:48,561 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:42:49,204 - main - <module> - INFO - program_started
2024-05-06 17:42:49,204 - uvicorn.error - INFO - Started server process [7727]
2024-05-06 17:42:49,205 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:42:49,205 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:43:00,363 - uvicorn.access - send - INFO - 127.0.0.1:38302 - "GET /docs HTTP/1.1" 200
2024-05-06 17:43:00,536 - uvicorn.access - send - INFO - 127.0.0.1:38302 - "GET /openapi.json HTTP/1.1" 200
2024-05-06 17:43:08,180 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:43:08,202 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:43:08,219 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': False, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:43:08,238 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:43:08,239 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:43:08,239 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_d32f6a17cb584c898f66a5ccaacc14d3 LIMIT 15 OFFSET 0]
2024-05-06 17:43:08,439 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:43:08,502 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:43:08,502 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-06 17:43:08,534 - uvicorn.access - send - INFO - 127.0.0.1:38316 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:43:20,814 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:43:20,835 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:43:20,851 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:43:20,881 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:43:20,881 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:43:20,882 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_ad430ff52f3c4295bea8284a1e6bf451 LIMIT 15 OFFSET 0]
2024-05-06 17:43:21,075 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:43:21,126 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:43:21,127 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4409, in get_pma_billing
    row["clientid"],row["orderid"],None,row["totalamt"],
TypeError: string indices must be integers
2024-05-06 17:43:21,136 - root - get_pma_billing - INFO - None
2024-05-06 17:43:21,165 - uvicorn.access - send - INFO - 127.0.0.1:50598 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:43:37,956 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:43:38,011 - uvicorn.error - INFO - Shutting down
2024-05-06 17:43:38,112 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:43:38,113 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:43:38,113 - uvicorn.error - INFO - Finished server process [7727]
2024-05-06 17:43:38,290 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:43:38,994 - main - <module> - INFO - program_started
2024-05-06 17:43:38,995 - uvicorn.error - INFO - Started server process [7935]
2024-05-06 17:43:38,995 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:43:38,995 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:43:43,122 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:43:43,187 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:43:43,216 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:43:43,250 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:43:43,250 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:43:43,251 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_25a5d42ba5d2451da18a7c8f6f1a520b LIMIT 15 OFFSET 0]
2024-05-06 17:43:43,449 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:43:43,496 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:43:43,497 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4410, in get_pma_billing
    datetime.date.today(),row["totalamt"],row["orderdescription"],datetime.date.today(),
KeyError: 'orderdescription'
2024-05-06 17:43:43,505 - root - get_pma_billing - INFO - None
2024-05-06 17:43:43,531 - uvicorn.access - send - INFO - 127.0.0.1:55454 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:43:54,499 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:43:54,562 - uvicorn.error - INFO - Shutting down
2024-05-06 17:43:54,662 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:43:54,663 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:43:54,663 - uvicorn.error - INFO - Finished server process [7935]
2024-05-06 17:43:54,841 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:43:55,356 - main - <module> - INFO - program_started
2024-05-06 17:43:55,356 - uvicorn.error - INFO - Started server process [8005]
2024-05-06 17:43:55,357 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:43:55,357 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:43:58,509 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:43:58,530 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:43:58,544 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:43:58,570 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:43:58,571 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:43:58,571 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_9ed2719a53714faaad1f4f8c4b6ede38 LIMIT 15 OFFSET 0]
2024-05-06 17:43:58,771 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:43:58,817 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:43:58,818 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4411, in get_pma_billing
    row["totalbaseamt"],row["totaltaxamt"],row["entity"],givenowtime(),payload['user_id'],False
KeyError: 'entity'
2024-05-06 17:43:58,826 - root - get_pma_billing - INFO - None
2024-05-06 17:43:58,856 - uvicorn.access - send - INFO - 127.0.0.1:58520 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:44:05,857 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:44:05,877 - uvicorn.error - INFO - Shutting down
2024-05-06 17:44:05,978 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:44:05,978 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:44:05,978 - uvicorn.error - INFO - Finished server process [8005]
2024-05-06 17:44:06,175 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:44:06,716 - main - <module> - INFO - program_started
2024-05-06 17:44:06,717 - uvicorn.error - INFO - Started server process [8055]
2024-05-06 17:44:06,717 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:44:06,718 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:44:10,104 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:44:10,125 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:44:10,139 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:44:10,160 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:44:10,160 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:44:10,160 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_7ba7dc69de944d92a98d1d769db9bc13 LIMIT 15 OFFSET 0]
2024-05-06 17:44:10,371 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:44:10,417 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:44:10,417 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-06 17:44:10,606 - uvicorn.access - send - INFO - 127.0.0.1:58640 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:44:20,006 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:44:20,033 - uvicorn.error - INFO - Shutting down
2024-05-06 17:44:20,134 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:44:20,135 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:44:20,135 - uvicorn.error - INFO - Finished server process [8055]
2024-05-06 17:44:20,304 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:44:20,860 - main - <module> - INFO - program_started
2024-05-06 17:44:20,861 - uvicorn.error - INFO - Started server process [8116]
2024-05-06 17:44:20,861 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:44:20,861 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:45:09,756 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:45:09,794 - uvicorn.error - INFO - Shutting down
2024-05-06 17:45:09,895 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:45:09,896 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:45:09,896 - uvicorn.error - INFO - Finished server process [8116]
2024-05-06 17:45:10,083 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:45:10,641 - main - <module> - INFO - program_started
2024-05-06 17:45:10,642 - uvicorn.error - INFO - Started server process [8317]
2024-05-06 17:45:10,642 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:45:10,643 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:45:51,914 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:45:51,954 - uvicorn.error - INFO - Shutting down
2024-05-06 17:45:52,055 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:45:52,056 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:45:52,057 - uvicorn.error - INFO - Finished server process [8317]
2024-05-06 17:45:52,208 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:45:52,801 - main - <module> - INFO - program_started
2024-05-06 17:45:52,801 - uvicorn.error - INFO - Started server process [8485]
2024-05-06 17:45:52,802 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:45:52,802 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:45:55,793 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:45:55,814 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:45:55,829 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:45:55,856 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:45:55,857 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:45:55,857 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_a5dac17eefcf41058dbb8748d6a6d8ef LIMIT 15 OFFSET 0]
2024-05-06 17:45:56,059 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:45:56,112 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:45:56,112 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4406, in get_pma_billing
    cursor.execute('select * from {tbl}')
psycopg2.errors.SyntaxError: syntax error at or near "{"
LINE 1: select * from {tbl}
                      ^

2024-05-06 17:45:56,131 - root - get_pma_billing - INFO - None
2024-05-06 17:45:56,142 - uvicorn.access - send - INFO - 127.0.0.1:36170 - "POST /getPMABilling HTTP/1.1" 500
2024-05-06 17:45:56,142 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/e/cura/cura_backend/./main.py", line 4424, in get_pma_billing
    cursor.execute(f'drop view {tbl}')
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2024-05-06 17:46:05,187 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:46:05,267 - uvicorn.error - INFO - Shutting down
2024-05-06 17:46:05,368 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:46:05,369 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:46:05,369 - uvicorn.error - INFO - Finished server process [8485]
2024-05-06 17:46:05,521 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:46:06,103 - main - <module> - INFO - program_started
2024-05-06 17:46:06,103 - uvicorn.error - INFO - Started server process [8542]
2024-05-06 17:46:06,104 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:46:06,104 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:46:09,101 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:46:09,122 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:46:09,140 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:46:09,162 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:46:09,162 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:46:09,162 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_c3ac73b5109d471fb88359186a2cb61d LIMIT 15 OFFSET 0]
2024-05-06 17:46:09,364 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:46:09,413 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:46:09,413 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4411, in get_pma_billing
    row["clientid"],row["orderid"],None,row["totalamt"],
TypeError: tuple indices must be integers or slices, not str
2024-05-06 17:46:09,464 - root - get_pma_billing - INFO - None
2024-05-06 17:46:09,499 - uvicorn.access - send - INFO - 127.0.0.1:51938 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:47:18,524 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:47:18,589 - uvicorn.error - INFO - Shutting down
2024-05-06 17:47:18,690 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:47:18,691 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:47:18,692 - uvicorn.error - INFO - Finished server process [8542]
2024-05-06 17:47:18,842 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:47:19,429 - main - <module> - INFO - program_started
2024-05-06 17:47:19,430 - uvicorn.error - INFO - Started server process [8837]
2024-05-06 17:47:19,430 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:47:19,431 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:47:23,151 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:47:23,172 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:47:23,188 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:47:23,209 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:47:23,209 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:47:23,209 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_bc7add6c8cc24635a726026d651a2e6b LIMIT 15 OFFSET 0]
2024-05-06 17:47:23,384 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:47:23,433 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:47:23,434 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-06 17:47:23,434 - root - filterAndPaginate_v2 - INFO -  Prepared final query [SELECT * FROM get_pma_billing_view_bc7add6c8cc24635a726026d651a2e6b]
2024-05-06 17:47:23,583 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 134
2024-05-06 17:47:23,617 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4407, in get_pma_billing
    rows = cursor.fetchall()
psycopg2.ProgrammingError: no results to fetch
2024-05-06 17:47:23,625 - root - get_pma_billing - INFO - None
2024-05-06 17:47:23,655 - uvicorn.access - send - INFO - 127.0.0.1:40738 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:47:43,450 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:47:43,508 - uvicorn.error - INFO - Shutting down
2024-05-06 17:47:43,609 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:47:43,609 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:47:43,609 - uvicorn.error - INFO - Finished server process [8837]
2024-05-06 17:47:43,781 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:47:44,428 - main - <module> - INFO - program_started
2024-05-06 17:47:44,429 - uvicorn.error - INFO - Started server process [8942]
2024-05-06 17:47:44,429 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:47:44,429 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:47:47,233 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:47:47,256 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:47:47,272 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:47:47,299 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:47:47,300 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:47:47,300 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_c6e2f2fe348e4cebbe7510748f549631 LIMIT 15 OFFSET 0]
2024-05-06 17:47:47,493 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:47:47,541 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:47:47,541 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-06 17:47:47,541 - root - filterAndPaginate_v2 - INFO -  Prepared final query [SELECT * FROM get_pma_billing_view_c6e2f2fe348e4cebbe7510748f549631]
2024-05-06 17:47:47,704 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 134
2024-05-06 17:47:47,744 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4410, in get_pma_billing
    row["clientid"],row["orderid"],None,row["totalamt"],
TypeError: tuple indices must be integers or slices, not str
2024-05-06 17:47:47,753 - root - get_pma_billing - INFO - None
2024-05-06 17:47:47,790 - uvicorn.access - send - INFO - 127.0.0.1:52716 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:48:05,019 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:48:05,039 - uvicorn.error - INFO - Shutting down
2024-05-06 17:48:05,140 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:48:05,140 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:48:05,140 - uvicorn.error - INFO - Finished server process [8942]
2024-05-06 17:48:05,327 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:48:05,935 - main - <module> - INFO - program_started
2024-05-06 17:48:05,935 - uvicorn.error - INFO - Started server process [9032]
2024-05-06 17:48:05,936 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:48:05,936 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:50:00,209 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:50:00,250 - uvicorn.error - INFO - Shutting down
2024-05-06 17:50:00,351 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:50:00,352 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:50:00,352 - uvicorn.error - INFO - Finished server process [9032]
2024-05-06 17:50:00,525 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:50:01,093 - main - <module> - INFO - program_started
2024-05-06 17:50:01,093 - uvicorn.error - INFO - Started server process [9489]
2024-05-06 17:50:01,093 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:50:01,094 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:50:04,004 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:50:04,029 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:50:04,045 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:50:04,070 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:50:04,070 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:50:04,071 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_1a27e18985a1407fb2ae67729ee49bc1 LIMIT 15 OFFSET 0]
2024-05-06 17:50:04,271 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:50:04,316 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:50:04,317 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4408, in get_pma_billing
    rows = runInTryCatch(conn,'get_pma_billing',isPaginationRequired=False,whereinquery=False,formatData=True,isdeleted=False)
TypeError: runInTryCatch() missing 1 required positional argument: 'payload'
2024-05-06 17:50:04,325 - root - get_pma_billing - INFO - None
2024-05-06 17:50:04,353 - uvicorn.access - send - INFO - 127.0.0.1:47536 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:50:16,566 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:50:16,588 - uvicorn.error - INFO - Shutting down
2024-05-06 17:50:16,689 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:50:16,689 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:50:16,689 - uvicorn.error - INFO - Finished server process [9489]
2024-05-06 17:50:16,869 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:50:17,533 - main - <module> - INFO - program_started
2024-05-06 17:50:17,533 - uvicorn.error - INFO - Started server process [9560]
2024-05-06 17:50:17,534 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:50:17,534 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:50:19,932 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:50:19,952 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:50:19,968 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:50:19,988 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:50:19,989 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:50:19,989 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_19627cf3c32941828772092bbdccc292 LIMIT 15 OFFSET 0]
2024-05-06 17:50:20,163 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:50:20,218 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:50:20,218 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4409, in get_pma_billing
    for row in rows['data']:
TypeError: 'coroutine' object is not subscriptable
2024-05-06 17:50:20,226 - root - get_pma_billing - INFO - None
/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py:191: RuntimeWarning: coroutine 'runInTryCatch' was never awaited
  return await dependant.call(**values)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2024-05-06 17:50:20,251 - uvicorn.access - send - INFO - 127.0.0.1:52614 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:50:33,689 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:50:33,790 - uvicorn.error - INFO - Shutting down
2024-05-06 17:50:33,891 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:50:33,891 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:50:33,892 - uvicorn.error - INFO - Finished server process [9560]
2024-05-06 17:50:34,061 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:50:34,663 - main - <module> - INFO - program_started
2024-05-06 17:50:34,664 - uvicorn.error - INFO - Started server process [9634]
2024-05-06 17:50:34,664 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:50:34,665 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:50:36,912 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:50:36,930 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:50:36,949 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:50:36,974 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:50:36,974 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:50:36,974 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_db31daf5080e49879b8ea043cb84f0a0 LIMIT 15 OFFSET 0]
2024-05-06 17:50:37,175 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:50:37,223 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:50:37,224 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-06 17:50:37,225 - root - runInTryCatch - INFO - get_pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:50:37,238 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:50:37,239 - root - runInTryCatch - ERROR - get_pma_billing_EXCEPTION: <can't execute an empty query>
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 1712, in runInTryCatch
    msg = logMessage(cursor,query)
  File "/mnt/e/cura/cura_backend/./main.py", line 16, in logMessage
    cursor.execute(query,arr)
psycopg2.ProgrammingError: can't execute an empty query
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4409, in get_pma_billing
    for row in rows['data']:
TypeError: 'NoneType' object is not subscriptable
2024-05-06 17:50:37,248 - root - get_pma_billing - INFO - None
2024-05-06 17:50:37,283 - uvicorn.access - send - INFO - 127.0.0.1:57458 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:51:07,680 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:51:07,764 - uvicorn.error - INFO - Shutting down
2024-05-06 17:51:07,865 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:51:07,865 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:51:07,865 - uvicorn.error - INFO - Finished server process [9634]
2024-05-06 17:51:08,030 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:51:08,597 - main - <module> - INFO - program_started
2024-05-06 17:51:08,598 - uvicorn.error - INFO - Started server process [9773]
2024-05-06 17:51:08,598 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:51:08,599 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:51:13,034 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:51:13,112 - uvicorn.error - INFO - Shutting down
2024-05-06 17:51:13,212 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:51:13,213 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:51:13,213 - uvicorn.error - INFO - Finished server process [9773]
2024-05-06 17:51:13,395 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:51:14,055 - main - <module> - INFO - program_started
2024-05-06 17:51:14,056 - uvicorn.error - INFO - Started server process [9795]
2024-05-06 17:51:14,056 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:51:14,057 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:51:15,844 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:51:15,863 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:51:15,879 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:51:15,901 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:51:15,901 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:51:15,901 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_b3287130d58d49a8b2bd888b8fa908a7 LIMIT 15 OFFSET 0]
2024-05-06 17:51:16,101 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:51:16,150 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:51:16,150 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-06 17:51:16,151 - root - runInTryCatch - INFO - get_pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:51:16,161 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:51:16,162 - root - runInTryCatch - ERROR - get_pma_billing_EXCEPTION: <can't execute an empty query>
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 1712, in runInTryCatch
    msg = logMessage(cursor,query)
  File "/mnt/e/cura/cura_backend/./main.py", line 16, in logMessage
    cursor.execute(query,arr)
psycopg2.ProgrammingError: can't execute an empty query
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4407, in get_pma_billing
    for row in rows['data']:
TypeError: 'NoneType' object is not subscriptable
2024-05-06 17:51:16,171 - root - get_pma_billing - INFO - None
2024-05-06 17:51:16,200 - uvicorn.access - send - INFO - 127.0.0.1:49718 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:53:40,604 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:53:40,685 - uvicorn.error - INFO - Shutting down
2024-05-06 17:53:40,786 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:53:40,787 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:53:40,787 - uvicorn.error - INFO - Finished server process [9795]
2024-05-06 17:53:40,945 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:53:41,484 - main - <module> - INFO - program_started
2024-05-06 17:53:41,484 - uvicorn.error - INFO - Started server process [10385]
2024-05-06 17:53:41,485 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:53:41,485 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:53:45,978 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:53:46,001 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:53:46,017 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:53:46,044 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:53:46,044 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:53:46,044 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_645b81afd8e54594bf882ccd17e58d79 LIMIT 15 OFFSET 0]
2024-05-06 17:53:46,234 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:53:46,287 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:53:46,287 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4415, in get_pma_billing
    msg = logMessage(cursor,query,[
  File "/mnt/e/cura/cura_backend/./main.py", line 16, in logMessage
    cursor.execute(query,arr)
psycopg2.errors.DatatypeMismatch: column "clientid" is of type integer but expression is of type record
LINE 1: ...t,tax,entityid,dated,createdby,isdeleted) VALUES ((3252, 271...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

2024-05-06 17:53:46,362 - root - get_pma_billing - INFO - None
2024-05-06 17:53:46,374 - uvicorn.access - send - INFO - 127.0.0.1:47516 - "POST /getPMABilling HTTP/1.1" 500
2024-05-06 17:53:46,374 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/e/cura/cura_backend/./main.py", line 4429, in get_pma_billing
    cursor.execute(f'drop view {tbl}')
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2024-05-06 17:54:34,165 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:54:34,186 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:54:34,202 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:54:34,232 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:54:34,232 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:54:34,232 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_ea27be8fcdeb4daa980218575135c0c6 LIMIT 15 OFFSET 0]
2024-05-06 17:54:34,420 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:54:34,471 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:54:34,471 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4415, in get_pma_billing
    msg = logMessage(cursor,query,[
  File "/mnt/e/cura/cura_backend/./main.py", line 16, in logMessage
    cursor.execute(query,arr)
psycopg2.errors.DatatypeMismatch: column "clientid" is of type integer but expression is of type record
LINE 1: ...t,tax,entityid,dated,createdby,isdeleted) VALUES ((3252, 271...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

2024-05-06 17:54:34,534 - root - get_pma_billing - INFO - None
2024-05-06 17:54:34,551 - uvicorn.access - send - INFO - 127.0.0.1:36660 - "POST /getPMABilling HTTP/1.1" 500
2024-05-06 17:54:34,551 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/e/cura/cura_backend/./main.py", line 4429, in get_pma_billing
    cursor.execute(f'drop view {tbl}')
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2024-05-06 17:54:40,372 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:54:40,392 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:54:40,413 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:54:40,440 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:54:40,441 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:54:40,441 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_e70b82e920a04d728f03b51a97c12a85 LIMIT 15 OFFSET 0]
2024-05-06 17:54:40,654 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:54:40,700 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:54:40,701 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4415, in get_pma_billing
    msg = logMessage(cursor,query,[
  File "/mnt/e/cura/cura_backend/./main.py", line 16, in logMessage
    cursor.execute(query,arr)
psycopg2.errors.DatatypeMismatch: column "clientid" is of type integer but expression is of type record
LINE 1: ...t,tax,entityid,dated,createdby,isdeleted) VALUES ((3252, 271...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

2024-05-06 17:54:40,762 - root - get_pma_billing - INFO - None
2024-05-06 17:54:40,773 - uvicorn.access - send - INFO - 127.0.0.1:42378 - "POST /getPMABilling HTTP/1.1" 500
2024-05-06 17:54:40,773 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/e/cura/cura_backend/./main.py", line 4429, in get_pma_billing
    cursor.execute(f'drop view {tbl}')
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2024-05-06 17:55:43,857 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:55:43,946 - uvicorn.error - INFO - Shutting down
2024-05-06 17:55:44,047 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:55:44,048 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:55:44,049 - uvicorn.error - INFO - Finished server process [10385]
2024-05-06 17:55:44,210 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:55:44,781 - main - <module> - INFO - program_started
2024-05-06 17:55:44,782 - uvicorn.error - INFO - Started server process [10885]
2024-05-06 17:55:44,782 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:55:44,782 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:55:47,909 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:55:47,929 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:55:47,945 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:55:48,002 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:55:48,002 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:55:48,002 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_974e59733d47449d93935d0ffb3fdf12 LIMIT 15 OFFSET 0]
2024-05-06 17:55:48,221 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:55:48,266 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:55:48,266 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4416, in get_pma_billing
    msg = logMessage(cursor,query,[
  File "/mnt/e/cura/cura_backend/./main.py", line 16, in logMessage
    cursor.execute(query,arr)
psycopg2.errors.DatatypeMismatch: column "clientid" is of type integer but expression is of type record
LINE 1: ...t,tax,entityid,dated,createdby,isdeleted) VALUES ((3252, 271...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

2024-05-06 17:55:48,383 - root - get_pma_billing - INFO - None
2024-05-06 17:55:48,394 - uvicorn.access - send - INFO - 127.0.0.1:36358 - "POST /getPMABilling HTTP/1.1" 500
2024-05-06 17:55:48,394 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/e/cura/cura_backend/./main.py", line 4430, in get_pma_billing
    cursor.execute(f'drop view {tbl}')
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2024-05-06 17:56:16,975 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:56:17,071 - uvicorn.error - INFO - Shutting down
2024-05-06 17:56:17,173 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:56:17,173 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:56:17,174 - uvicorn.error - INFO - Finished server process [10885]
2024-05-06 17:56:17,327 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:56:17,909 - main - <module> - INFO - program_started
2024-05-06 17:56:17,910 - uvicorn.error - INFO - Started server process [11019]
2024-05-06 17:56:17,910 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:56:17,910 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:56:21,502 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:56:21,523 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:56:21,543 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:56:21,569 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:56:21,569 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:56:21,569 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_4d02e27f56254c1db7462e52e69deb0a LIMIT 15 OFFSET 0]
2024-05-06 17:56:21,766 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:56:21,815 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:56:21,816 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4416, in get_pma_billing
    msg = logMessage(cursor,query,[
  File "/mnt/e/cura/cura_backend/./main.py", line 16, in logMessage
    cursor.execute(query,arr)
psycopg2.errors.SyntaxError: syntax error at or near ":"
LINE 1: ...332.640000000000000000, 1969.96800000000000000000):int,(3262...
                                                             ^

2024-05-06 17:56:21,888 - root - get_pma_billing - INFO - None
2024-05-06 17:56:21,900 - uvicorn.access - send - INFO - 127.0.0.1:36982 - "POST /getPMABilling HTTP/1.1" 500
2024-05-06 17:56:21,900 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rudra/.local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/rudra/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/e/cura/cura_backend/./main.py", line 4430, in get_pma_billing
    cursor.execute(f'drop view {tbl}')
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2024-05-06 17:56:44,470 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:56:44,561 - uvicorn.error - INFO - Shutting down
2024-05-06 17:56:44,662 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:56:44,663 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:56:44,663 - uvicorn.error - INFO - Finished server process [11019]
2024-05-06 17:56:44,849 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:56:45,513 - main - <module> - INFO - program_started
2024-05-06 17:56:45,514 - uvicorn.error - INFO - Started server process [11133]
2024-05-06 17:56:45,515 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:56:45,515 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:56:47,427 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:56:47,453 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:56:47,470 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:56:47,494 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:56:47,495 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:56:47,495 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_934248ab8ad541c9b47e0977562f9aa8 LIMIT 15 OFFSET 0]
2024-05-06 17:56:47,684 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:56:47,743 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:56:47,743 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4411, in get_pma_billing
    for row in _rows['data']:
TypeError: list indices must be integers or slices, not str
2024-05-06 17:56:47,799 - root - get_pma_billing - INFO - None
2024-05-06 17:56:47,825 - uvicorn.access - send - INFO - 127.0.0.1:45210 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:57:14,150 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:57:14,199 - uvicorn.error - INFO - Shutting down
2024-05-06 17:57:14,300 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:57:14,300 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:57:14,300 - uvicorn.error - INFO - Finished server process [11133]
2024-05-06 17:57:14,478 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:57:15,052 - main - <module> - INFO - program_started
2024-05-06 17:57:15,052 - uvicorn.error - INFO - Started server process [11255]
2024-05-06 17:57:15,053 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:57:15,053 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:57:17,721 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:57:17,743 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:57:17,761 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:57:17,798 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:57:17,799 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:57:17,799 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_55d075b0e9374eabb4b3912d844acd42 LIMIT 15 OFFSET 0]
2024-05-06 17:57:17,994 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:57:18,043 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:57:18,043 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
Traceback (most recent call last):
  File "/mnt/e/cura/cura_backend/./main.py", line 4416, in get_pma_billing
    msg = logMessage(cursor,query,[
  File "/mnt/e/cura/cura_backend/./main.py", line 16, in logMessage
    cursor.execute(query,arr)
ValueError: unsupported format character ',' (0x2c) at index 185
2024-05-06 17:57:18,102 - root - get_pma_billing - INFO - None
2024-05-06 17:57:18,123 - uvicorn.access - send - INFO - 127.0.0.1:33246 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:57:33,184 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:57:33,264 - uvicorn.error - INFO - Shutting down
2024-05-06 17:57:33,365 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:57:33,366 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:57:33,366 - uvicorn.error - INFO - Finished server process [11255]
2024-05-06 17:57:33,569 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:57:34,109 - main - <module> - INFO - program_started
2024-05-06 17:57:34,110 - uvicorn.error - INFO - Started server process [11336]
2024-05-06 17:57:34,110 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:57:34,111 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:57:37,038 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:57:37,060 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:57:37,074 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:57:37,102 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:57:37,102 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:57:37,102 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_39f015dd9d7646f5b96f71076ddea8f9 LIMIT 15 OFFSET 0]
2024-05-06 17:57:37,304 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:57:37,351 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:57:37,352 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-06 17:57:38,900 - uvicorn.access - send - INFO - 127.0.0.1:42572 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:58:05,020 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:58:05,073 - uvicorn.error - INFO - Shutting down
2024-05-06 17:58:05,174 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:58:05,175 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:58:05,175 - uvicorn.error - INFO - Finished server process [11336]
2024-05-06 17:58:05,366 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:58:06,000 - main - <module> - INFO - program_started
2024-05-06 17:58:06,001 - uvicorn.error - INFO - Started server process [11467]
2024-05-06 17:58:06,001 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:58:06,002 - uvicorn.error - INFO - Application startup complete.
2024-05-06 17:58:08,279 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:58:08,300 - root - get_pma_billing - INFO - CREATE VIEW
2024-05-06 17:58:08,315 - root - runInTryCatch - INFO - pma_billing:RT: received payload <{'user_id': 1234, 'month': 1, 'year': 2013, 'filters': [], 'sort_by': [], 'order': 'asc', 'add': True, 'pg_no': 1, 'pg_size': 15}>
2024-05-06 17:58:08,339 - root - check_role_access - INFO - QUERY IS : <SELECT roleid FROM usertable WHERE id = 1234>
2024-05-06 17:58:08,339 - root - runInTryCatch - INFO - Pagination
2024-05-06 17:58:08,339 - root - filterAndPaginate_v2 - INFO -  Prepared final query [select * from get_pma_billing_view_133b33c52d944b03bb549a82d0463f4f LIMIT 15 OFFSET 0]
2024-05-06 17:58:08,524 - root - filterAndPaginate_v2 - INFO - Cursor message is SELECT 15
2024-05-06 17:58:08,571 - root - filterAndPaginate_v2 - INFO -  Given filter yeilds <134> entries
2024-05-06 17:58:08,572 - root - runInTryCatch - INFO - Formatting in progress for process pma_billing
2024-05-06 17:58:10,583 - uvicorn.access - send - INFO - 127.0.0.1:55660 - "POST /getPMABilling HTTP/1.1" 200
2024-05-06 17:58:44,126 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 17:58:44,177 - uvicorn.error - INFO - Shutting down
2024-05-06 17:58:44,278 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 17:58:44,278 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 17:58:44,278 - uvicorn.error - INFO - Finished server process [11467]
2024-05-06 17:58:44,440 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 17:58:45,032 - main - <module> - INFO - program_started
2024-05-06 17:58:45,033 - uvicorn.error - INFO - Started server process [11627]
2024-05-06 17:58:45,033 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 17:58:45,034 - uvicorn.error - INFO - Application startup complete.
2024-05-06 22:18:28,323 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 22:18:28,339 - uvicorn.error - INFO - Shutting down
2024-05-06 22:18:28,445 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 22:18:28,449 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 22:18:28,451 - uvicorn.error - INFO - Finished server process [11627]
2024-05-06 22:18:28,870 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 22:18:30,109 - main - <module> - INFO - program_started
2024-05-06 22:18:30,110 - uvicorn.error - INFO - Started server process [69495]
2024-05-06 22:18:30,110 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 22:18:30,111 - uvicorn.error - INFO - Application startup complete.
2024-05-06 22:22:06,284 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 22:22:06,287 - uvicorn.error - INFO - Shutting down
2024-05-06 22:22:06,388 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 22:22:06,388 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 22:22:06,388 - uvicorn.error - INFO - Finished server process [69495]
2024-05-06 22:22:06,575 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 22:22:07,254 - main - <module> - INFO - program_started
2024-05-06 22:22:07,255 - uvicorn.error - INFO - Started server process [70543]
2024-05-06 22:22:07,255 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 22:22:07,255 - uvicorn.error - INFO - Application startup complete.
2024-05-06 22:22:16,893 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 22:22:16,982 - uvicorn.error - INFO - Shutting down
2024-05-06 22:22:17,083 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 22:22:17,083 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 22:22:17,083 - uvicorn.error - INFO - Finished server process [70543]
2024-05-06 22:22:17,284 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 22:22:17,813 - main - <module> - INFO - program_started
2024-05-06 22:22:17,814 - uvicorn.error - INFO - Started server process [70586]
2024-05-06 22:22:17,814 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 22:22:17,814 - uvicorn.error - INFO - Application startup complete.
2024-05-06 23:03:02,702 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 23:03:02,794 - uvicorn.error - INFO - Shutting down
2024-05-06 23:03:02,895 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 23:03:02,895 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 23:03:02,895 - uvicorn.error - INFO - Finished server process [70586]
2024-05-06 23:03:03,078 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 23:03:03,705 - main - <module> - INFO - program_started
2024-05-06 23:03:03,706 - uvicorn.error - INFO - Started server process [80299]
2024-05-06 23:03:03,706 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 23:03:03,706 - uvicorn.error - INFO - Application startup complete.
2024-05-06 23:03:22,190 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 23:03:22,258 - uvicorn.error - INFO - Shutting down
2024-05-06 23:03:22,359 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 23:03:22,360 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 23:03:22,360 - uvicorn.error - INFO - Finished server process [80299]
2024-05-06 23:03:22,544 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 23:03:23,193 - main - <module> - INFO - program_started
2024-05-06 23:03:23,193 - uvicorn.error - INFO - Started server process [80377]
2024-05-06 23:03:23,194 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 23:03:23,194 - uvicorn.error - INFO - Application startup complete.
2024-05-06 23:03:54,107 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 23:03:54,182 - uvicorn.error - INFO - Shutting down
2024-05-06 23:03:54,283 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 23:03:54,283 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 23:03:54,284 - uvicorn.error - INFO - Finished server process [80377]
2024-05-06 23:03:54,445 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 23:03:55,030 - main - <module> - INFO - program_started
2024-05-06 23:03:55,031 - uvicorn.error - INFO - Started server process [80505]
2024-05-06 23:03:55,031 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 23:03:55,031 - uvicorn.error - INFO - Application startup complete.
2024-05-06 23:04:57,783 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 23:04:57,804 - uvicorn.error - INFO - Shutting down
2024-05-06 23:04:57,905 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 23:04:57,905 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 23:04:57,905 - uvicorn.error - INFO - Finished server process [80505]
2024-05-06 23:04:58,114 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 23:04:58,680 - main - <module> - INFO - program_started
2024-05-06 23:04:58,680 - uvicorn.error - INFO - Started server process [80943]
2024-05-06 23:04:58,681 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 23:04:58,681 - uvicorn.error - INFO - Application startup complete.
2024-05-06 23:05:19,299 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 23:05:19,337 - uvicorn.error - INFO - Shutting down
2024-05-06 23:05:19,437 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 23:05:19,438 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 23:05:19,438 - uvicorn.error - INFO - Finished server process [80943]
2024-05-06 23:05:19,606 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 23:05:20,204 - main - <module> - INFO - program_started
2024-05-06 23:05:20,205 - uvicorn.error - INFO - Started server process [81034]
2024-05-06 23:05:20,205 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 23:05:20,206 - uvicorn.error - INFO - Application startup complete.
2024-05-06 23:33:45,722 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-06 23:33:45,806 - uvicorn.error - INFO - Shutting down
2024-05-06 23:33:45,906 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-06 23:33:45,907 - uvicorn.error - INFO - Application shutdown complete.
2024-05-06 23:33:45,907 - uvicorn.error - INFO - Finished server process [81034]
2024-05-06 23:33:46,070 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-06 23:33:46,788 - main - <module> - INFO - program_started
2024-05-06 23:33:46,789 - uvicorn.error - INFO - Started server process [87808]
2024-05-06 23:33:46,789 - uvicorn.error - INFO - Waiting for application startup.
2024-05-06 23:33:46,789 - uvicorn.error - INFO - Application startup complete.
2024-05-07 00:18:13,379 - uvicorn.error - WARNING - StatReload detected file change in 'main.py'. Reloading...
2024-05-07 00:18:13,423 - uvicorn.error - INFO - Shutting down
2024-05-07 00:18:13,524 - uvicorn.error - INFO - Waiting for application shutdown.
2024-05-07 00:18:13,525 - uvicorn.error - INFO - Application shutdown complete.
2024-05-07 00:18:13,525 - uvicorn.error - INFO - Finished server process [87808]
2024-05-07 00:18:13,714 - asyncio - __init__ - DEBUG - Using selector: EpollSelector
2024-05-07 00:18:14,316 - main - <module> - INFO - program_started
2024-05-07 00:18:14,317 - uvicorn.error - INFO - Started server process [98423]
2024-05-07 00:18:14,317 - uvicorn.error - INFO - Waiting for application startup.
2024-05-07 00:18:14,317 - uvicorn.error - INFO - Application startup complete.
